apiVersion: http.crossplane.io/v1alpha1
kind: DesposibleRequest
metadata:
  name: health-check
spec:
  deletionPolicy: Orphan
  forProvider:
    insecureSkipTLSVerify: true
    waitTimeout: 5m
    rollbackLimit: 5
    url: https://api.example.com/health
    method: POST
    body: |
      {
        "check_type": "simple",
        "additional_info": "optional"
      }
    headers:
      User-Agent: "Crossplane Health Checker"
  providerConfigRef:
    name: http-conf
# TODO: check if it's possible to modify the deletionPolicy to be orphan by default.
