apiVersion: http.crossplane.io/v1alpha2
kind: DisposableRequest
metadata:
  name: health-check
spec:
  # Secrets providing patches for request data
  requestSecretDataPatches:
    - name: my-secret
      namespace: default
      key: username
      toFieldPaths:
        - forProvider.headers.authorization[0]
        - forProvider.body.aaa
    - name: my-secret
      namespace: default
      key: password
      toFieldPaths:
        - forProvider.body.bb

  # Secrets receiving patches for response data
  responseSecretDataPatches: 
    - name: response-secret
      namespace: default
      key: extracted-data
      fromFieldPath:
        .Body.success

  deletionPolicy: Orphan
  forProvider:
    # The 'expectedResponse' field is optional. If used, also set 'rollbackRetriesLimit', which determines the number of HTTP requests to be sent until the jq query returns true.
    # expectedResponse: '.Body.job_status == "success"'
    insecureSkipTLSVerify: true
    waitTimeout: 5m
    rollbackRetriesLimit: 5
    url: https://enwgarmh79yh.x.pipedream.net/
    method: POST
    body: |
      {
        "check_type": "simple",
        "additional_info": "optional"
      }
    headers:
      User-Agent:
        - "Crossplane Health Checker"
    # 
  providerConfigRef:
    name: http-conf
# TODO: check if it's possible to modify the deletionPolicy to be orphan by default.
# 