apiVersion: http.crossplane.io/v1alpha2
kind: Request
metadata:
  name: laundry-ye
spec:
  forProvider:
    insecureSkipTLSVerify: true
    waitTimeout: 5m
    headers:
      Content-Type:
        - application/json
      Authorization:
        - ("Bearer {{ auth:default:token }}{{auth-new:default:token}}")
    payload:
      baseUrl: http://host.docker.internal:5000/todo
      body: |
        {
          "name": "Do Laundry {{ auth:default:token }}", 
          "reminder": "Every 1 hour", 
          "responsible": "Dan",
          "password": "secretdata {{ password:crossplane-system:secretKey }}"
        }
    mappings:
      - method: "POST"
        body: |
          {
            todo_name: .payload.body.name, 
            reminder: .payload.body.reminder, 
            responsible: .payload.body.responsible,
          }
        url: .payload.baseUrl
      - method: "GET"
        url: (.payload.baseUrl + "/" + (.response.body.id|tostring))
      - method: "PUT"
        body: |
          {
            todo_name: .payload.body.name, 
            reminder: .payload.body.reminder, 
            responsible: .payload.body.responsible
          }
        url: (.payload.baseUrl + "/" + (.response.body.id|tostring))
      - method: "DELETE"
        url: (.payload.baseUrl + "/" + (.response.body.id|tostring))
    
    # Secrets receiving patches from response data
    secretInjectionConfigs: 
      - secretRef:
          name: response-secret
          namespace: default
        secretKey: extracted-data
        responsePath: .body.reminder
      - secretRef:
          name: new-secret
          namespace: default
        secretKey: extracted-data
        responsePath: .body.reminder
  providerConfigRef:
    name: http-conf
