# TODO: add headers for payload

apiVersion: http.crossplane.io/v1alpha1
kind: Request
metadata:
  name: laundry-by-dan
spec:
  forProvider:
    headers:
      Content-Type:
        - application/json
        - application/xml
    payload:
      baseUrl: "https://mytryings.free.beeceptor.com"
      body: '{
        "name": "Do Laundry", 
        "reminder": "Every 1 hour", 
        "responsible": "Dan"
        }'
    mappings:
      - method: "POST"
        body: '{
          "todo_name": ".payload.body.name", 
          "reminder": ".payload.body.reminder", 
          "responsible": ".payload.body.responsible"
          }'
        url: .payload.baseUrl
      - method: "GET"
        url: (.payload.baseUrl + "/" + (.response.body.id|tostring)) 
      - method: "PUT"
        body: '{
          "todo_name": ".payload.body.name", 
          "reminder": ".payload.body.reminder", 
          "responsible": ".payload.body.responsible"
          }'
        url: (.payload.baseUrl + "/" + (.response.body.id|tostring)) 
      - method: "DELETE"
        url: (.payload.baseUrl + "/" + (.response.body.id|tostring)) 
  providerConfigRef:
    name: http-conf