apiVersion: http.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: http-conf
spec:
  credentials:
    source: Secret
    # The value of this secret will be used to set the "Authorization" header for all requests made with this config.
    # It will be added as: "Authorization": "<secret-value>".
    secretRef:
      namespace: crossplane-system
      name: http-provider-secret
      key: token
